sudo: false
language: python
cache:
- pip
install:
- pip install -r requirements.txt
script:
- echo "Hello"
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: simsemand
  password: ${PASSWORD}
  skip_existing: true
