sudo: false

language: python

cache:
  - pip

install:
  - pip install -r requirements.txt

script:
  - echo "Hello"


deploy:
  provider: pypi
  twine_version: 1.12.1
  user: __token__
  password:
    secure: bqui1s66TaKHhNMVAHnwgIXKuF2aUoklMNSA2o8GoexEHpGqJG0cHiPngw8rKkE6eDhS/A99l4GlJigzMqWh8glK17AR14/DVwPi0EaDN2xdGTQ8xh6h2irJK4VMm6PAkuj00Idk5BZDX+WFV/j3qDdEmOcCw0ze5hJAfXsV0TiF5WRRGps3RnbGwa4pXZGMNCS6juEKi/QQ7l1c/yIvHspIBWCPsiWYZ3b128zaSTmsLU6bFElQX1u8/5r0mJc4gd0cVWtYrCJz98fQE4d5uelB5QI5S5h4/XLNSRzBATF8HYRsggA6xYiKUMKRUyo5GouMeaipyPu0QsgH6OK5wMsrTIbg9qeRO41ptSFwwJvEl4wzNLbDvPRsJMBd/6IY6HVOC3iHBNAgMk0My0DdQh1jhMETdAIgclDtse7WCgO0uninJpSuqxBfmxdt0bWn1dxt90O8rUpeRRLdaVKX9Z2q8IFgFw69mGTRXYVuXUUs0erEcuevQ/UVYLdunM/tiJyfVgUXF9/QMZUnqCENYvzrr8gdMzYLETi10S508sb1XLzxrtFV7UTR31tBkS+pi6Rjg68jtEihvEDIEma3ANl1mA+DF5LCGIWzVEOINZp0ry4Sj53qPPgaU67c0dHKLc/vFFp0KHR7UeyCXhPsDe5yZbVD0DD/ljOEtWL0w0A=
  skip_existing: true
