sudo: false
language: python
cache:
- pip
install:
- pip install -r requirements.txt
script:
- echo "Hello"
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: __token__
  password:
    secure: 1O5/BhjfE/aDWFPPha+wsU6G6N900mbakX7ep3nHR/nJPKAt3Ul2s14h7Ipf0KalvgybnyIu8kUN7D2BjPbnRP/nWsaoZX5DhJkIIr1PlcfGBuFtO8r1z15Cd+hXo9sE6x+vX21MQuH0Ka1QzsP6heb8zVHDR53XNFRwordJDmHiIB9+Xps1urxreykdqKvoq5R9bnjSRup1HDzGwINLcSAup/GiwhkfUQgbcuKbK7XZMHeEJ4jUSEW5zreqZpfojZnDujRbmyRZJ1zKZ7YpqODYOBTfcnib3zsSeFhpGzZ0IO9c/lVvryhvLRti1J/kjQMy2bJBzUhlxcVGO2KkYfT9heJhGCy8kwKcTXAZQ0oPrXr/hheOu5GQmLABcV1Wysp45qJgzw9o2GK87yacqhb7GuXWevDzUY7HeY01GIahSi7njar+zPRZdyyU0hRuYrWnY0L7x1uj3gPCUgeYOVTXVrQgZwfpqjEof+TKr/oARV3jVFy/T0AU3sLKFGJa30GhD9HHKufhbb3ySDSw+tc3R6cahGe2RYEOrfKWZrRoIreIYQOV4xpGzSfyxZJJnkH8QW9h4CeiuSb/UVNpkJrTH3AgSbt3rYTBzPTcL19Vh5D/S5jFHjTbAHBCAlAhdG3oEjjYXiabwafhooy3LcL2r6B5Lw0vh0+lhRFYBwc=
  skip_existing: true
